### ISSUE TITLE
Sidebar menu should show all active screens + a close button

### ISSUE THREAD

**Issue by ToniHeiss** [sibvisions/flutter_jvx#144] opened 2023-05-11 11:55 UTC
The current side menu only shows the currently active route/screen. It should show all currently opened screens. Additionally, it should show a close icon on the right hand side to close this screen, but only when it is opened (opened meaning in opened in general, not just when it is the currently active route!)

Only to be done after: #143

**Comment by Bungeefan** [comment] 2023-05-12 08:07
There seems to be a weird bug that needs further researching, which blocks us from closing the current screen via the close button on mobile.
Therefore, I am going to disable the close button for the current screen (for now).

Bug:
Having for example "First" open and then opening "Second" and finally trying to close "Second" via the Sidebar Menu.
Even though we are correctly routing and rebuilding the new (old) screen, Flutter still shows the now old WorkScreen on top of the new one, which shouldn't even be possible.
Still unclear if it's "our" bug, on the behalf of the Beamer package or Flutter itself.

**Comment by ToniHeiss** [comment] 2023-05-12 08:11
I have a workaround planned, will test that out later.

**Comment by rjahn** [comment] 2023-05-12 08:12
Test: Add a simple close button to our screen wrapper.

I guess it's because of drawer runs in another "context". What about a future close? First, close the drawer and after it's closed, close the screen.

**Comment by Bungeefan** [comment] 2023-05-12 08:18
@ToniHeiss No, I haven't had the time yet to create it, still finishing commits.
But will try asap.

**Comment by Bungeefan** [comment] 2023-05-12 12:28
@rjahn This problem has nothing to do with our context as the BeamerDelegate that we use to beam is not depending on any context.
Additionally, even a significant delayed (5s) beaming doesn't work. So also no future close.

@ToniHeiss Your idea about `maybePop` or `pop` also didn't work, the only difference is that this will trigger our `WillPopScope` which then sends a second CloseScreenCommand that errors without any difference in routing behavior.

I am now trying to reproduce this in another project.
However, I am still very confused on why a normal `beamBack` in our screen works fine but not after some commands in a processor, independent of any contexts.

**Comment by ToniHeiss** [comment] 2023-05-12 12:32
Close this ticket if the rest is done and works. Remove the X for the current active screen. Make another ticket for this specific bug with the current screen beeing deleted. So that at least this feature ticket is marked as done. The bug in itself is only relevant for this small niche feature, for which we already have the button on the upper left corner to leave the screen/force close it. There is no inherent benefit of allowing the current screen to be closed through the side menu as well. 

Reason for the other ticket is just to track the bug and maybe get a bug ticket going for flutter.

**Comment by ToniHeiss** [comment] 2023-05-12 12:33
Only beeing able to close other screens not yet opened does not trigger the bug and is good enough for this to be markes as complete. I would say beeing able to close the current screen is just a nice to have, not a must have.

**Comment by Bungeefan** [comment] 2023-05-12 12:36
X for the current screen was already removed in the first commit.
Closing.

**Closed by Bungeefan** 2023-05-12 12:36 UTC
Labels: enhancement
